# frozen_string_literal: true

module Unidpp
  module Registry
    # A registry item: the single definition (I2 — single definition, many
    # constraints) of a data element, profile, transform, crypto suite,
    # trust anchor or unit. Item references are (register, item, version).
    # Profiles constrain and compose; they never redefine — where regions
    # regulate differently they register distinct items.
    #
    # Profile items embed their ProfileManifest, version-pinned to one of
    # the item's versions (seam S4: version pinning at the profile↔registry
    # join).
    class Item < Lutaml::Model::Serializable
      ITEM_CLASSES = %w[
        data-element profile crypto-suite transform trust-anchor unit
      ].freeze

      class UnknownVersionError < Unidpp::Error; end

      attribute :identifier, :string
      attribute :register, :string
      attribute :item_class, :string, values: ITEM_CLASSES
      attribute :title, :string
      # ISO 19135 submitting organization for this item.
      attribute :submitting_organization, :string
      attribute :versions, ItemVersion, collection: true, default: -> { [] }
      attribute :manifest, ProfileManifest

      json do
        map "identifier", to: :identifier
        map "register", to: :register, render_nil: false
        map "item_class", to: :item_class
        map "title", to: :title, render_nil: false
        map "submitting_organization", to: :submitting_organization, render_nil: false
        map "versions", to: :versions
        map "manifest", to: :manifest, render_nil: false
      end

      yaml do
        map "identifier", to: :identifier
        map "register", to: :register, render_nil: false
        map "item_class", to: :item_class
        map "title", to: :title, render_nil: false
        map "submitting_organization", to: :submitting_organization, render_nil: false
        map "versions", to: :versions
        map "manifest", to: :manifest, render_nil: false
      end

      # item_class predicates (profile? / unit? / ...) are generated by
      # lutaml-model from the item_class value enumeration.

      # @param number [String]
      # @return [ItemVersion, nil]
      def version(number)
        versions.find { |v| v.version == number.to_s }
      end

      # @param number [String]
      # @return [ItemVersion]
      # @raise [UnknownVersionError]
      def version!(number)
        version(number) ||
          raise(UnknownVersionError, "#{identifier} has no version #{number}")
      end

      # Versions in registration order (by effective_from, then version).
      #
      # @return [Array<ItemVersion>]
      def ordered_versions
        versions.sort_by do |v|
          [v.effective_from || DateTime.new(0), v.version.to_s]
        end
      end

      # The version currently in force: latest effective version with
      # status "valid".
      #
      # @return [ItemVersion, nil]
      def current_version
        reversed = ordered_versions.reverse
        reversed.find(&:valid?) || reversed.find { |v| !v.retired? }
      end

      # Follows supersession links from the earliest version carrying one
      # (or from +from+, when given) to the terminal version.
      #
      # @param from [String, nil] version number to start from
      # @return [Array<ItemVersion>] the chain, in supersession order
      def supersession_chain(from: nil)
        start = from ? version!(from) : ordered_versions.first
        chain = [start]
        while (next_number = chain.last.superseded_by_version)
          chain << version!(next_number)
        end
        chain
      end

      # Resolved effective window end: explicit effective_until, else the
      # successor's effective_from, else open (nil).
      #
      # @param version_number [String]
      # @return [DateTime, nil]
      def window_until(version_number)
        v = version!(version_number)
        return v.effective_until if v.effective_until
        return nil if v.superseded_by_version.nil?

        version(v.superseded_by_version)&.effective_from
      end

      # The version in force at time +t+ (point-in-time registry state).
      #
      # @param t [Time, DateTime]
      # @return [ItemVersion, nil]
      def in_force_at(t)
        t = t.is_a?(DateTime) ? t : DateTime.parse(t.to_s)
        ordered_versions
          .select { |v| v.in_force_at?(t, until_time: window_until(v.version)) }
          .last
      end

      # Seam S4 discipline: an embedded manifest must be pinned to a
      # version of this item.
      #
      # @return [Boolean]
      def manifest_version_pinned?
        manifest.nil? || !version(manifest.version).nil?
      end
    end
  end
end
