# frozen_string_literal: true

require "securerandom"
require "digest"

module Unidpp
  # Append-only, hash-chained event log with salted commitments (I4, S6).
  #
  # Chain rule: each entry's commitment is
  #
  #   SHA-256( canonical_json(event) || salt || previous_commitment )
  #
  # where canonical_json is the framework (lutaml-model) serialization of
  # the event under a deterministic key order. The salt disciplines the
  # log↔transparency-log seam: logs anchor commitments, never facts — a
  # reveal (event + salt) must remain inclusion-consistent with every
  # past commitment ("commit now, reveal later, never contradict").
  class EventLog
    class IntegrityError < Unidpp::Error; end

    # The commitment envelope of one event. (De)serialization is generated
    # by lutaml-model — no hand-rolled to_h / from_h.
    class Entry < Lutaml::Model::Serializable
      attribute :event, Event
      attribute :salt, :string           # hex — the disclosure key
      attribute :previous, :string       # hex commitment of prior entry
      attribute :commitment, :string     # hex commitment of this entry

      json do
        map "event", to: :event
        map "salt", to: :salt
        map "previous", to: :previous
        map "commitment", to: :commitment
      end

      yaml do
        map "event", to: :event
        map "salt", to: :salt
        map "previous", to: :previous
        map "commitment", to: :commitment
      end
    end

    # Serialized form of a whole log. (De)serialization is generated by
    # lutaml-model — no hand-rolled to_h / from_h.
    class Document < Lutaml::Model::Serializable
      attribute :subject, :string
      attribute :algorithm, :string, default: -> { "sha256" }
      attribute :entries, Entry, collection: true, default: -> { [] }

      json do
        map "subject", to: :subject
        map "algorithm", to: :algorithm
        map "entries", to: :entries
      end

      yaml do
        map "subject", to: :subject
        map "algorithm", to: :algorithm
        map "entries", to: :entries
      end
    end

    # Commitment of the empty log (genesis value of the chain).
    GENESIS = "0" * 64
    ALGORITHM = "sha256"

    attr_reader :document

    def initialize(subject:, entries: [])
      @document = Document.new(subject: subject, algorithm: ALGORITHM,
                               entries: entries)
      @document.entries.freeze
    end

    # -- append-only writer ---------------------------------------------------

    # Appends +event+ with a fresh salt, chaining onto the current head.
    # The event's id is assigned here exactly once (if the caller did not
    # set one) so the committed canonical form is stable; existing
    # entries are never touched.
    #
    # @param event [Event]
    # @param salt [String] disclosure key (generated when omitted)
    # @return [Entry]
    def append(event, salt: SecureRandom.hex(16))
      event.event_id ||= SecureRandom.uuid
      entry = Entry.new(event: event, salt: salt, previous: head,
                        commitment: nil)
      entry.commitment = commitment_for(entry.event, entry.salt,
                                        entry.previous)
      new_entries = @document.entries + [entry]
      @document = Document.new(subject: @document.subject,
                               algorithm: @document.algorithm,
                               entries: new_entries)
      @document.entries.freeze
      entry
    end

    # -- queries ---------------------------------------------------------------

    # @return [Array<Entry>]
    def entries
      @document.entries
    end

    def events
      entries.map(&:event)
    end

    def empty?
      entries.empty?
    end

    # Head commitment: the value a transparency log anchors.
    #
    # @return [String] hex
    def head
      entries.last&.commitment || GENESIS
    end
    alias commitment head

    def subject
      @document.subject
    end

    # Notarized as-of state: the contiguous sub-log of events that had
    # occurred at +t+. The sub-chain re-verifies because chaining is
    # prefix-consistent.
    #
    # @param t [Time, DateTime]
    # @return [EventLog]
    def as_of(t)
      t = t.is_a?(DateTime) ? t : DateTime.parse(t.to_s)
      EventLog.new(subject: subject,
                   entries: entries.select do |e|
                     !e.event.occurred_at.nil? && e.event.occurred_at <= t
                   end)
    end

    # The reveal pair for an entry — the material a counterparty needs to
    # check inclusion-consistency of a past commitment.
    #
    # @param event_id [String]
    # @return [Entry, nil]
    def reveal(event_id)
      entries.find { |e| e.event.event_id == event_id }
    end

    # -- integrity ---------------------------------------------------------------

    # @return [Array<String>] human-readable integrity problems, [] when
    #   the chain is sound
    def integrity_errors
      errors = []
      previous = GENESIS
      entries.each_with_index do |entry, index|
        if entry.previous != previous
          errors << "entry #{index} (#{entry.event.event_type}): " \
                    "previous #{entry.previous.inspect} != #{previous.inspect}"
        end
        expected = commitment_for(entry.event, entry.salt, entry.previous)
        if entry.commitment != expected
          errors << "entry #{index} (#{entry.event.event_type}): " \
                    "commitment does not cover the stored event+salt"
        end
        previous = entry.commitment
      end
      errors
    end

    # @return [Boolean]
    def valid?
      integrity_errors.empty?
    end

    # @raise [IntegrityError] on the first problem found
    def verify!
      errors = integrity_errors
      return self if errors.empty?

      raise IntegrityError, errors.first
    end

    # Inclusion-consistency of a reveal: recomputing the commitment from
    # the revealed event and salt must reproduce the anchored commitment.
    #
    # @param entry [Entry]
    # @return [Boolean]
    def consistent_reveal?(entry)
      entry.commitment == commitment_for(entry.event, entry.salt,
                                         entry.previous)
    end

    # -- framework serialization -------------------------------------------------

    def self.from_yaml(yaml)
      document = Document.from_yaml(yaml)
      new(subject: document.subject, entries: document.entries)
    end

    def self.from_json(json)
      document = Document.from_json(json)
      new(subject: document.subject, entries: document.entries)
    end

    def to_yaml
      @document.to_yaml
    end

    def to_json(*_args)
      @document.to_json
    end

    private

    # SHA-256 over the canonical JSON of the event, the salt and the
    # previous commitment.
    def commitment_for(event, salt, previous)
      Digest::SHA256.hexdigest(
        [CanonicalJson.of(event), salt, previous].join("\n")
      )
    end
  end
end
