# frozen_string_literal: true

module Unidpp
  # Scheme-agnostic product identifier (framework layer L0, invariant I1:
  # one subject, one identity, never re-minted).
  #
  # Parses the identity carriers the framework must bridge:
  # * GS1 Digital Link URIs — https://id.example.com/01/09506000134352/10/LOT/21/SER
  # * GS1 human-readable element strings — (01)09506000134352(10)LOT(21)SER
  # * ISO/IEC 15459-style unique identifiers — [00]006141411234567890 (SSCC)
  # * GB/T 33993-style national carrier wrappers — an https URL whose path
  #   embeds a GTIN-13/GTIN-14, with optional lot/serial query parameters
  # * plain URNs, including urn:epc:id:sgtin/sscc forms
  #
  # The parsed model normalizes the GS1 components (gtin, lot, serial,
  # sscc) and derives the identifier granularity (model / batch / item per
  # the identity lattice: bare GTIN -> model, +lot -> batch, +serial or
  # SSCC -> item).
  #
  # (De)serialization is generated by lutaml-model from the attribute +
  # mapping declarations below — no hand-rolled to_h / from_h.
  class ProductIdentifier < Lutaml::Model::Serializable
    class ParseError < Unidpp::Error; end

    SCHEMES = %w[gs1-dl gs1-element iso-15459 gbt-33993 urn other].freeze
    GRANULARITIES = %w[model batch item].freeze

    attribute :scheme, :string, values: SCHEMES, default: -> { "other" }
    # Original carrier value exactly as encountered.
    attribute :value, :string
    attribute :granularity, :string, values: GRANULARITIES,
                                      default: -> { "model" }
    # Normalized GS1 components (nil when absent).
    attribute :gtin, :string          # canonical GTIN-14
    attribute :lot, :string           # AI (10)
    attribute :serial, :string        # AI (21)
    attribute :sscc, :string          # SSCC-18, ISO/IEC 15459 transport unit

    json do
      map "scheme", to: :scheme
      map "value", to: :value
      map "granularity", to: :granularity
      map "gtin", to: :gtin, render_nil: false
      map "lot", to: :lot, render_nil: false
      map "serial", to: :serial, render_nil: false
      map "sscc", to: :sscc, render_nil: false
    end

    yaml do
      map "scheme", to: :scheme
      map "value", to: :value
      map "granularity", to: :granularity
      map "gtin", to: :gtin, render_nil: false
      map "lot", to: :lot, render_nil: false
      map "serial", to: :serial, render_nil: false
      map "sscc", to: :sscc, render_nil: false
    end

    # -- parsing ------------------------------------------------------------

    # @param input [String] carrier value
    # @return [ProductIdentifier]
    # @raise [ParseError] when no parser claims the input
    def self.parse(input)
      s = input.to_s.strip
      raise ParseError, "blank identifier" if s.empty?

      if s.match?(/\Aurn:/i)
        parse_urn(s)
      elsif s.match?(/\Ahttps?:\/\//i)
        parse_web_uri(s)
      elsif s.match?(/\A[\(\[]\d{2,4}[\)\]]/)
        parse_element_string(s)
      else
        raise ParseError, "unrecognized identifier syntax: #{s}"
      end
    end

    # @param input [String] parenthesized / bracketed element string
    def self.parse_element_string(input)
      values = Gs1.parse_element_string(input)
      Gs1.validate_identity_ais!(values)
      if values["00"]
        new(scheme: "iso-15459", value: input, sscc: values["00"],
            granularity: "item")
      elsif values["01"]
        new(scheme: "gs1-element", value: input, gtin: values["01"],
             lot: values["10"], serial: values["21"],
             granularity: granularity_for(values["21"], values["10"]))
      else
        raise ParseError, "no identity AI (00/01) in #{input}"
      end
    end

    # @param input [String] GS1 Digital Link or GB/T 33993-style URI
    def self.parse_web_uri(input)
      uri = URI.parse(input)
      segments = uri.path.to_s.split("/").reject(&:empty?)
      if dl_identity_pairs?(segments)
        values = segments.each_slice(2).to_h
        Gs1.validate_identity_ais!(values)
        if values["00"]
          new(scheme: "gs1-dl", value: input, sscc: values["00"],
              granularity: "item")
        else
          new(scheme: "gs1-dl", value: input, gtin: values["01"],
              lot: values["10"], serial: values["21"],
              granularity: granularity_for(values["21"], values["10"]))
        end
      elsif (gtin = gbt33993_gtin(segments))
        params = URI.decode_www_form(uri.query.to_s).to_h
        new(scheme: "gbt-33993", value: input, gtin: gtin,
            lot: params["lot"], serial: params["serial"],
            granularity: granularity_for(params["serial"], params["lot"]))
      else
        raise ParseError, "unrecognized identifier URI: #{input}"
      end
    rescue URI::InvalidURIError => e
      raise ParseError, "invalid identifier URI: #{e.message}"
    end

    # @param input [String] plain or EPC URN
    def self.parse_urn(input)
      urn = input.downcase
      if urn.start_with?("urn:epc:id:sgtin:")
        parse_sgtin_urn(input)
      elsif urn.start_with?("urn:epc:id:sscc:")
        parse_sscc_urn(input)
      else
        new(scheme: "urn", value: input)
      end
    end

    # urn:epc:id:sgtin:<companyPrefix>.<itemRef>.<serial>
    # prefix+itemRef total 12 digits (GTIN-13 base) or 13 digits (GTIN-14
    # base with leading indicator digit).
    def self.parse_sgtin_urn(input)
      parts = input.split(":").last.split(".")
      raise ParseError, "malformed sgtin URN: #{input}" unless parts.size == 3

      prefix, item_ref, serial = parts
      base = "#{prefix}#{item_ref}"
      unless /\A\d{12,13}\z/.match?(base)
        raise ParseError,
              "sgtin company prefix + item ref must total 12 or 13 digits"
      end

      gtin14 = base.length == 13 ? base : "0#{base}"
      new(scheme: "urn", value: input,
          gtin: "#{gtin14}#{Gs1.check_digit(base)}",
          serial: serial, granularity: "item")
    end

    # urn:epc:id:sscc:<companyPrefix>.<ssccDigits>
    def self.parse_sscc_urn(input)
      parts = input.split(":").last.split(".")
      raise ParseError, "malformed sscc URN: #{input}" unless parts.size == 2

      joined = parts.join
      sscc =
        if joined.length == 17
          "#{joined}#{Gs1.check_digit(joined)}"
        elsif joined.length == 18
          joined
        else
          raise ParseError, "sscc URN must carry 17 or 18 digits: #{input}"
        end
      raise ParseError, "invalid SSCC check digit in #{input}" unless Gs1.valid_check_digit?(sscc)

      new(scheme: "urn", value: input, sscc: sscc, granularity: "item")
    end

    # -- derived identity ----------------------------------------------------

    # Canonical human-readable form. GS1-based schemes canonicalize to the
    # element string in ascending AI order, so the same product expressed
    # as Digital Link or element string yields the same canonical form.
    #
    # @return [String]
    def canonical
      case scheme
      when "gs1-dl", "gs1-element"
        %w[01 10 21].filter_map do |ai|
          v = { "01" => gtin, "10" => lot, "21" => serial }[ai]
          "(#{ai})#{v}" if v
        end.join
      when "iso-15459"
        sscc ? "(00)#{sscc}" : value.to_s
      else
        value.to_s
      end
    end

    # Stable identity key across representations: scheme-independent for
    # GS1-keyed identifiers, scheme-qualified otherwise.
    #
    # @return [String]
    def canonical_id
      if gtin
        "gtin:#{gtin}#{lot ? "/lot:#{lot}" : ''}#{serial ? "/ser:#{serial}" : ''}"
      elsif sscc
        "sscc:#{sscc}"
      elsif scheme == "urn"
        value.to_s
      else
        "#{scheme}:#{value}"
      end
    end

    # Granularity predicates (model? / batch? / item?) are generated by
    # lutaml-model from the granularity value enumeration.

    # @return [Boolean] check digits valid for the carried GS1 keys
    def valid_keys?
      [gtin, sscc].compact.all? { |key| Gs1.valid_check_digit?(key) }
    end

    def to_s
      canonical
    end

    private_class_method def self.granularity_for(serial, lot)
      serial ? "item" : (lot ? "batch" : "model")
    end

    private_class_method def self.dl_identity_pairs?(segments)
      return false unless segments.size.even? && segments.size >= 2

      segments.each_slice(2).all? { |ai, _| Gs1::DL_PATH_AIS.include?(ai) }
    end

    private_class_method def self.gbt33993_gtin(segments)
      segments.filter_map do |segment|
        next unless /\A\d{13,14}\z/.match?(segment)

        segment if Gs1.valid_check_digit?(segment)
      end.first
    end
  end
end
