# frozen_string_literal: true

require "securerandom"
require "digest"

module Unidpp
  # Temporal interval of a link's validity.
  class LinkInterval < Lutaml::Model::Serializable
    attribute :from, "Lutaml::Model::Type::DateTime"
    attribute :until, "Lutaml::Model::Type::DateTime"

    json do
      map "from", to: :from, render_nil: false
      map "until", to: :until, render_nil: false
    end

    yaml do
      map "from", to: :from, render_nil: false
      map "until", to: :until, render_nil: false
    end

    # @param t [Time, DateTime]
    # @return [Boolean]
    def covers?(t)
      t = t.is_a?(DateTime) ? t : DateTime.parse(t.to_s)
      (!from || t >= from) && (!self.until || t < self.until)
    end
  end

  # Typed relationship edge between passports (I5). Edge types carry
  # different legal and lifecycle semantics:
  #
  #   association    R1 loose (compatibility, supply) — navigational only
  #   derivation     R2 ancestral (split/mix/refine/remanufacture)
  #   installation   R3 structural parent<->child, temporal (see below)
  #   type-lineage   R4 type versioning, derived types, config vectors
  #   profile-of     R5 lens<->core (not a passport-to-passport edge)
  #   custody        R6 social/control edges, orthogonal to structure
  #   membership     R7 group nodes (shipments, kits, recall sets)
  #
  # Installation is its own event class, not generic containment: an
  # installed component is a different legal object from the standalone
  # one (permanent alteration, pairing, lifecycle coupling, and
  # bidirectional parent knowledge — with the disclosure hazard that
  # creates, hence visibility classes and salted parent commitments:
  # proof-of-binding without knowledge-of-parent, I12).
  #
  # (De)serialization is generated by lutaml-model from the attribute +
  # mapping declarations below — no hand-rolled to_h / from_h.
  class PassportLink < Lutaml::Model::Serializable
    TYPES = %w[
      association derivation installation type-lineage profile-of custody membership
    ].freeze
    DIRECTIONS = %w[upstream downstream undirected].freeze
    BINDING_METHODS = %w[
      none fastened soldered glued welded potted integrated keyed
    ].freeze
    RECOVERABILITY = %w[restorable harvestable destructive absorbing].freeze
    PAIRINGS = %w[none firmware key module].freeze
    VISIBILITIES = %w[public restricted blind escrowed].freeze
    ESCROWS = %w[none trustee].freeze

    attribute :link_type, :string, values: TYPES
    attribute :direction, :string, values: DIRECTIONS,
                                   default: -> { "downstream" }
    attribute :child, ProductIdentifier
    attribute :parent, ProductIdentifier
    attribute :interval, LinkInterval
    # Binding strength: how the child is held by the parent.
    attribute :binding_method, :string, values: BINDING_METHODS,
                                        default: -> { "none" }
    # Recoverability spectrum determines identity continuity:
    #   restorable   disassembly restores a marketable standalone object
    #   harvestable  recovered but altered; continues with parent history
    #   destructive  child ceases; flows to material passport (derivation)
    #   absorbing    identity dissolves (paint, adhesive)
    attribute :recoverability, :string, values: RECOVERABILITY
    # Parent-scoped slot identity ("battery slot 1 of car X").
    attribute :slot_id, :string
    # Pairing / re-identification on install.
    attribute :pairing, :string, values: PAIRINGS, default: -> { "none" }
    # Permanent alterations performed by the installation.
    attribute :alterations, :string, collection: true, default: -> { [] }
    # Edge visibility class (I12): blind is the consumer-install default —
    # a child->parent edge reveals where a thing is.
    attribute :visibility, :string, values: VISIBILITIES,
                                    default: -> { "public" }
    attribute :escrow, :string, values: ESCROWS, default: -> { "none" }
    attribute :audiences, :string, collection: true, default: -> { [] }
    # Proof-of-binding (blind edges): salted commitment to the parent,
    # stored in the child's log; verifiable without revealing the parent.
    attribute :parent_commitment, :string
    attribute :commitment_salt, :string

    json do
      map "link_type", to: :link_type
      map "direction", to: :direction
      map "child", to: :child, render_nil: false
      map "parent", to: :parent, render_nil: false
      map "interval", to: :interval, render_nil: false
      map "binding_method", to: :binding_method
      map "recoverability", to: :recoverability, render_nil: false
      map "slot_id", to: :slot_id, render_nil: false
      map "pairing", to: :pairing
      map "alterations", to: :alterations, render_nil: false
      map "visibility", to: :visibility
      map "escrow", to: :escrow
      map "audiences", to: :audiences, render_nil: false
      map "parent_commitment", to: :parent_commitment, render_nil: false
      map "commitment_salt", to: :commitment_salt, render_nil: false
    end

    yaml do
      map "link_type", to: :link_type
      map "direction", to: :direction
      map "child", to: :child, render_nil: false
      map "parent", to: :parent, render_nil: false
      map "interval", to: :interval, render_nil: false
      map "binding_method", to: :binding_method
      map "recoverability", to: :recoverability, render_nil: false
      map "slot_id", to: :slot_id, render_nil: false
      map "pairing", to: :pairing
      map "alterations", to: :alterations, render_nil: false
      map "visibility", to: :visibility
      map "escrow", to: :escrow
      map "audiences", to: :audiences, render_nil: false
      map "parent_commitment", to: :parent_commitment, render_nil: false
      map "commitment_salt", to: :commitment_salt, render_nil: false
    end

    # -- construction ---------------------------------------------------------

    # Builds an installation edge (R3) with the full binding schema. When
    # +visibility+ is blind (the consumer-install default), the parent is
    # replaced by a salted commitment: the child proves it is validly
    # installed in *some* parent without revealing which. The salt is the
    # disclosure key (escrowed or revealed at ceremony).
    #
    # @return [PassportLink]
    def self.install(child:, parent:, visibility: "blind",
                     salt: SecureRandom.hex(16), **attrs)
      link = new(link_type: "installation", direction: "downstream",
                 child: child, parent: parent, visibility: visibility,
                 **attrs)
      if visibility == "blind"
        link.parent = nil
        link.parent_commitment = PassportLink.parent_commitment(child,
                                                                parent, salt)
        link.commitment_salt = salt
      end
      link
    end

    # @return [String] hex SHA-256 over the canonical child and parent
    #   identities and the salt
    def self.parent_commitment(child, parent, salt)
      Digest::SHA256.hexdigest(
        [child.canonical, parent.canonical, salt].join("\n")
      )
    end

    # -- queries --------------------------------------------------------------

    # Edge-type and visibility predicates (installation? / blind? /
    # escrowed?) are generated by lutaml-model from the corresponding
    # value enumerations.

    def hidden_parent?
      blind? && parent.nil? && !parent_commitment.nil?
    end

    # Does disassembly of this installation restore a marketable object
    # with identity continuity? (R3 vs R2 boundary.)
    def identity_continuity?
      %w[restorable harvestable].include?(recoverability)
    end

    # Proof-of-binding check. For visible edges this is identity equality;
    # for blind edges the candidate parent is recomputed against the
    # stored salted commitment — full disclosure by ceremony only.
    #
    # @param candidate [ProductIdentifier] the parent being tested
    # @return [Boolean]
    def proves_parent?(candidate)
      return false if candidate.nil?

      if parent
        parent.canonical == candidate.canonical
      elsif parent_commitment
        PassportLink.parent_commitment(child, candidate,
                                       commitment_salt) == parent_commitment
      else
        false
      end
    end
  end
end
