# frozen_string_literal: true

require "bigdecimal"

module Unidpp
  # Quantity = value + registered unit URI (the units chain: ISO 80000 ->
  # UnitsDB/UnitsML -> OpenCDD mirror). Units are *registered URIs*, not
  # bare symbols; unit conversion is a registered transform (deterministic
  # factors from the registry), so this class never converts implicitly —
  # arithmetic requires identical unit URIs and raises on mismatch. The
  # twin stores canonical measured values in canonical units only; no
  # pre-transformed duplicates.
  #
  # Measurement uncertainty is mandatory metadata on measured values
  # (published MTF): it is carried as a standard (k=1) uncertainty with
  # its coverage factor, and conformity decisions near a boundary follow
  # the ILAC-G8/JCGM-106 shared-risk rule (measured values agree when
  # |difference| <= expanded combined uncertainty).
  #
  # (De)serialization is generated by lutaml-model from the attribute +
  # mapping declarations below — no hand-rolled to_h / from_h.
  class Quantity < Lutaml::Model::Serializable
    class UnitMismatchError < Unidpp::Error; end

    # Standard uncertainty with coverage factor.
    class Uncertainty < Lutaml::Model::Serializable
      attribute :value, :decimal
      attribute :coverage_factor, :decimal, default: -> { BigDecimal("2") }

      json do
        map "value", to: :value
        map "coverage_factor", to: :coverage_factor
      end

      yaml do
        map "value", to: :value
        map "coverage_factor", to: :coverage_factor
      end

      # @return [BigDecimal] expanded uncertainty U = k * u
      def expanded
        value * coverage_factor
      end
    end

    attribute :value, :decimal
    # Registered unit URI, e.g. "https://unitsml.org/unit#kWh" or the
    # UnitsDB identifier URI for the unit.
    attribute :unit, :string
    attribute :uncertainty, Uncertainty

    json do
      map "value", to: :value
      map "unit", to: :unit
      map "uncertainty", to: :uncertainty, render_nil: false
    end

    yaml do
      map "value", to: :value
      map "unit", to: :unit
      map "uncertainty", to: :uncertainty, render_nil: false
    end

    # -- strict-unit arithmetic ------------------------------------------------

    def +(other)
      assert_same_unit(other)
      Quantity.new(value: value + other.value, unit: unit,
                   uncertainty: combine_uncertainty(other))
    end

    def -(other)
      assert_same_unit(other)
      Quantity.new(value: value - other.value, unit: unit,
                   uncertainty: combine_uncertainty(other))
    end

    # Scalar multiple (unit unchanged); scaling does not apply to
    # uncertainties.
    def *(factor)
      Quantity.new(value: value * factor, unit: unit)
    end

    def zero?
      value.zero?
    end

    def negative?
      value.negative?
    end

    def positive?
      value.positive?
    end

    # @param other [Quantity]
    # @return [Boolean] same registered unit URI
    def compatible_with?(other)
      unit == other.unit
    end

    # ILAC-G8 shared-risk conformity decision: two measured values agree
    # when their absolute difference is within the expanded combined
    # uncertainty (U = k * sqrt(u1^2 + u2^2), k = the larger coverage
    # factor). Values without uncertainties agree only on exact equality.
    #
    # @param other [Quantity]
    # @return [Boolean]
    def agrees_with?(other)
      assert_same_unit(other)
      return value == other.value unless uncertainty && other.uncertainty

      (value - other.value).abs <= expanded_combined_uncertainty(other)
    end

    # @param other [Quantity]
    # @return [BigDecimal] k * sqrt(u1^2 + u2^2), nil when uncertainless
    def expanded_combined_uncertainty(other)
      return nil unless uncertainty && other.uncertainty

      k = [uncertainty.coverage_factor,
           other.uncertainty.coverage_factor].max
      sum_of_squares = uncertainty.value * uncertainty.value +
                       other.uncertainty.value * other.uncertainty.value
      k * BigDecimal(sum_of_squares.sqrt(10))
    end

    private

    def assert_same_unit(other)
      return if compatible_with?(other)

      raise UnitMismatchError,
            "unit mismatch: #{unit} vs #{other.unit} — convert through a " \
            "registered transform, never implicitly"
    end

    def combine_uncertainty(other)
      return nil unless uncertainty && other.uncertainty

      Uncertainty.new(
        value: BigDecimal(Math.sqrt(
          (uncertainty.value * uncertainty.value +
           other.uncertainty.value * other.uncertainty.value).to_f
        )),
        coverage_factor: uncertainty.coverage_factor
      )
    end
  end
end
