# frozen_string_literal: true

module Unidpp
  # Verification verdict (I9 / I13): graded, never boolean. A verdict
  # states which verification *reading* it answers, the *freshness* class
  # of the underlying state, and a coverage report (which data points the
  # verdict covers and which are missing).
  #
  # The three readings (because law needs all three):
  #   evidentiary     what could a diligent verifier know at T, given the
  #                   then-current trust state (protects good-faith actors)
  #   current_state   fraud voids ab initio — prevents laundering
  #   cryptographic   signature/chain validity alone
  #
  # Freshness verdicts degrade explicitly, never silently:
  #   fresh            within the profile's freshness window
  #   stale            past the window; still served, marked
  #   offline_degraded served from Tier-A carrier / cache, as-of stamped
  #   unavailable      no current state could be established
  class Verdict < Lutaml::Model::Serializable
    READINGS = %w[evidentiary current_state cryptographic].freeze
    FRESHNESS = %w[fresh stale offline_degraded unavailable].freeze

    attribute :reading, :string, values: READINGS
    attribute :freshness, :string, values: FRESHNESS
    attribute :rendered_at, "Lutaml::Model::Type::DateTime"
    # Coverage report: data point URIs covered by this verdict and still
    # missing for the profile that asked.
    attribute :covered, :string, collection: true, default: -> { [] }
    attribute :missing, :string, collection: true, default: -> { [] }
    attribute :notes, :string, collection: true, default: -> { [] }

    json do
      map "reading", to: :reading
      map "freshness", to: :freshness
      map "rendered_at", to: :rendered_at, render_nil: false
      map "covered", to: :covered, render_nil: false
      map "missing", to: :missing, render_nil: false
      map "notes", to: :notes, render_nil: false
    end

    yaml do
      map "reading", to: :reading
      map "freshness", to: :freshness
      map "rendered_at", to: :rendered_at, render_nil: false
      map "covered", to: :covered, render_nil: false
      map "missing", to: :missing, render_nil: false
      map "notes", to: :notes, render_nil: false
    end

    # Reading predicates (evidentiary? / current_state? / cryptographic?)
    # are generated by lutaml-model from the reading value enumeration.

    # I13: degradation is explicit — anything not fresh is degraded and
    # must be marked, never silently passed.
    def degraded?
      freshness != "fresh"
    end

    def complete?
      missing.empty?
    end

    # @return [Rational, nil] covered / (covered + missing), nil when empty
    def coverage_ratio
      total = covered.size + missing.size
      return nil if total.zero?

      Rational(covered.size, total)
    end
  end
end
